version: "3.8"

services:
  protein_analyzer:
    build: .
    container_name: protein_analyzer
    volumes:
      - .:/app
      - ./data/input:/app/data/input   # for input files
      - ./data/output:/app/data/output   # for output files (extracted and inferred)
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
